version: "3.1"

services:
  wildfly:
    image: quay.io/wildfly/wildfly:27.0.0.Final-jdk17
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - "./target/Cnss-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war"
    env_file: .env

  mariadb:
    image: mariadb:10.10
    volumes:
      - "database:/var/lib/mysql"
    ports:
      - "3307:3306"
    env_file: .env

volumes:
  database: